Automated Trading Systems and Artificial Intelligence

In [6]:
import pandas as pd 
import yfinance as yf

Defining Parameters from Dataset collected from the Yahoo Finance Library

In [7]:
import datetime as dt
from datetime import datetime

start_date='2015-01-02'
today=datetime.today().strftime("%Y-%m-%d")

Define a function to load the dataset from Yahoo Finance

In [11]:
def load_data(ticker):
    data=yf.download(ticker, start_date, today)
    data.reset_index(inplace=True)
    return data

We call the function and load the dataset but we would be focusing on a partcular Currency pair (EUR/USD)

In [13]:
df = load_data("EURUSD=X")
df.sample(n=5)

[*********************100%***********************]  1 of 1 completed

           Date      Open      High       Low     Close  Adj Close  Volume
2245 2023-08-16  1.090417  1.093470  1.089776  1.090417   1.090417       0
1275 2019-11-27  1.102208  1.102208  1.099336  1.102256   1.102256       0
145  2015-07-24  1.098841  1.099602  1.092790  1.098901   1.098901       0
1009 2018-11-19  1.141214  1.146289  1.139445  1.141396   1.141396       0
2488 2024-07-22  1.089918  1.090156  1.087370  1.089918   1.089918       0

In [14]:
df.shape

(2545, 7)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2545 entries, 0 to 2544
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       2545 non-null   datetime64[ns]
 1   Open       2545 non-null   float64
 2   High       2545 non-null   float64
 3   Low        2545 non-null   float64
 4   Close      2545 non-null   float64
 5   Adj Close  2545 non-null   float64
 6   Volume     2545 non-null   int64
dtypes: datetime64[ns](1), float64(5), int64(1)
memory usage: 139.3 KB

We do not need the Adj_close and volume column, so we would drop them.

In [21]:
df=df.drop(['Adj Close', 'Volume'], axis=1)
df.head()

        Date      Open      High       Low     Close  Day  Month  Year
0 2015-01-02  1.208868  1.208956  1.201080  1.208941    2      1  2015
1 2015-01-05  1.195500  1.197590  1.188909  1.194643    5      1  2015
2 2015-01-06  1.193830  1.197000  1.188693  1.193902    6      1  2015
3 2015-01-07  1.187479  1.190000  1.180401  1.187536    7      1  2015
4 2015-01-08  1.183894  1.184806  1.175601  1.183600    8      1  2015

In [22]:
df['Day']=df['Date'].dt.day
df['Month']=df['Date'].dt.month
df['Year']=df['Date'].dt.year
df.head()

        Date      Open      High       Low     Close  Day  Month  Year
0 2015-01-02  1.208868  1.208956  1.201080  1.208941    2      1  2015
1 2015-01-05  1.195500  1.197590  1.188909  1.194643    5      1  2015
2 2015-01-06  1.193830  1.197000  1.188693  1.193902    6      1  2015
3 2015-01-07  1.187479  1.190000  1.180401  1.187536    7      1  2015
4 2015-01-08  1.183894  1.184806  1.175601  1.183600    8      1  2015